catalog.api.url=https://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations/LcgvWelfarelist
catalog.api.service-key=76f5502d8c86b1852cecedc3e8656d8bafaa838bcf87435f917c7ae633c7ff37

# ?? ??? ?? (test html )
spring.web.resources.static-locations=classpath:/static/